[git]
auto-local-bookmark = true
push-new-bookmarks = true

[ui]
diff.format = "git"
pager = "delta"

# taken from https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-13034102
[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))'
'immutable_heads()' = "builtin_immutable_heads() | remote_bookmarks()"

[aliases]
tug = ["util", "exec", "--", "sh", "-c", """
if [ "x$1" = "x" ]; then
  jj bookmark move --from "closest_bookmark(@)" --to "closest_pushable(@)"
else
  jj bookmark move --to "closest_pushable(@)" "$@"
fi
""", ""]
c = ["commit"]
cb = ["new", "-B @","--no-edit", "-m"]
ca = ["new", "-A @","--no-edit", "-m"]
ci = ["commit", "--interactive"]
e = ["edit"]
i = ["git", "init", "--colocate"]
nb = ["bookmark", "create", "-r @-"] # "new bookmark"
pull = ["git", "fetch"]
push = ["git", "push", "--allow-new"]
r = ["rebase"]
s = ["squash"]
sa = ["squash", "-u", "--into"]
si = ["squash", "--interactive"]

[user]
email = "juan.sanchez.montalvo@youview.com"
name = "Juan A. Sanchez"
