theme = "catppuccin_mocha"

[keys.normal]
C-c = ":wa"
y = "yank_main_selection_to_clipboard"
p = "paste_clipboard_before"


[keys.insert]
C-c = "normal_mode"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor]
color-modes = true